name: tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - xarray
  - rioxarray
  - openpyxl
  - pip
  - netCDF4
  - pytorch
  - torchvision
  - pyarrow
  - black
  - pip:
    - jupyter-book
    - matplotlib
    - ghp-import
    - wis-downloader
    - PIL
    - hydrodataset